buyerName:
- cici
- jerry
buyerPassword:
- cici321654
- jerry321654
captcha: '1512'
managerName: admin
managerPassword: mtx_15908
mobile_code: '908908'
sellerName: shamoseller
sellerPassword: mtxseller
